//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKutuphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int ID { get; set; }
        public string KitapAd { get; set; }
        public Nullable<int> Yazar { get; set; }
        public Nullable<int> Tur { get; set; }
        public string SayfaSayisi { get; set; }
        public string Hakkinda { get; set; }
        public string Yayınevi { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual KitapTur KitapTur { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
